services:
  book-drop:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: book-drop
    restart: unless-stopped
    ports:
      - '${PORT:-3001}:${PORT:-3001}'
    cpus: 1.0
    mem_limit: 1g
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
    env_file:
      - path: .env
        required: false
    environment:
      - PORT
